export const EventName = {
    JOIN_GAME_SUCCESS: "JOIN_GAME_SUCCESS",
    SPIN_PRESS: "SPIN_PRESS",
    UPDATE_BET_SIZE: "UPDATE_BET_SIZE",
    UPDATE_TABLE: "UPDATE_TABLE",
    RECEIVE_SPIN_RESULT: "RECEIVE_SPIN_RESULT",
    SPIN_REQUEST: "SPIN_REQUEST",
    FINISH_SHOW_RESULT: "FINISH_SHOW_RESULT",

}